Improve string format and crediting of contributors
pablo-s/passes pull request #39
Opened 2023-11-15 00:46 UTC by turtlegarden

**Note**: I was sadly unable to recompile the po files after I had made these changes due to a dependency issue. Once you recompile them, I can credit the translators properly and add a Swedish translation.

2023-11-15 15:03 UTC, TheEvilSkeleton requested changes

2023-11-15 15:03 UTC, TheEvilSkeleton commented on src/main.py
> +            "Hari Rana",
Thanks for adding me as a contributor :)
```suggestion
            "Hari Rana (TheEvilSkeleton) https://tesk.page",
```

2023-11-15 18:49 UTC, pablo-s commented
Thanks to both of you for the time spent on improving Passes!

If I am not mistaken, these are the changes proposed in this pull request: (1) add contributors, (2) formatting Blueprint and Python files, (3) changing in some texts, (4) development profile.

I really like the change 1. Especially using the changes proposed by @TheEvilSkeleton .

I am not sure I want number 2. But please, let me know if I am missing something. Why is it better this other format? In general, I do prefer having the opening curly bracket in its own line.

About number 3, is it better to capitalize all words in sentences? For example: "Import A Pass" is better than "Import a pass"

Regarding change 4, it may be that it brings something useful, such as the devel header bar. But, apart from this, why do you think this is a good addition to this project?

2023-11-17 08:18 UTC, pablo-s commented
Thank you @turtlegarden !

I am still not sure about the re-formating of the code. Either Python or Blueprint files. However, I will consider using formatters in the future.

Regarding the rest of the changes, I think I would be happy with them. Is it fine with you creating independent pull requests for each set of changes? I think it is too much for a single one.

2024-09-03 10:47 UTC, closed without merging